### ISSUE TITLE
Usar Sefaz Homologacao

### ISSUE THREAD

**Issue by crmmvio** [GRMagic/Sefaz#25]
Poderia adicionar nos exemplos o uso para o Ambiente de Homologação

**Comment by crmmvio** [comment]
Descuple não entendi foi feito nesse post mergeado?

**Comment by GRMagic** [comment]
Foi feito um pull request e nesse pull request tem o exemplo de como usar o pacote em ambiente de homologação.

https://github.com/GRMagic/Sefaz/blob/f1a618c3519a2437c0e79621c2a79af90b6ec952/src/Sefaz.Exemplo/Program.cs#L21
