### ISSUE TITLE
Erro de SSL/TLS ao realizar a consulta da NF-e pela chave

### ISSUE THREAD

**Issue by willpower18** [GRMagic/Sefaz#28]
Prezados ao tentar realizar  a consulta da NF-e a partir da aplicação web (.net 6) rodando em um Azure App Service, estamos tomando este erro, o TLS está configurado em 1.2 e a aplicação está rodando sobre SSL, alguma sugestão de como resolver este problema?

Segue erro abaixo:

Could not establish trust relationship for the ssl/tls secure channel with authority "www1.nfe.fazenda.gov.br"

**Comment by GRMagic** [comment]
Eu tive uma problema semelhante um tempo atrás quando estava usando a aplicação em um ambiente on-premise.
No meu caso o problema era que a empresa usava um proxy que estava configurado para abrir os pacotes criptografados, o que causava uma falha de segurança na criptogravia do canal. Eles resolveram o problema adicionando uma regra de firewall que permitia a aplicação acessar a internet diretamente, sem passar pelo proxy. Nenhuma alteração no programa de download foi necessária.

**Comment by GRMagic** [comment]
Quando conseguir resolver, poste aqui a solução.
