### ISSUE TITLE
Consistencia do CNPJ

### ISSUE THREAD

**Issue by DanielSartori** [GRMagic/Sefaz#29]
O Programa esta consistindo o CNPJ com 14 digitos, mas quando mandamos o CNJ com zeros a esquerda ele nao reconhece os zeros e reclama que o CNPJ nao tem 14 digitos!

**Comment by GRMagic** [comment]
Boa noite,

Você pode mostrar o trecho de código onde isso está acontecendo? Estou pelo celular agora, mas costumo usar o tipo string para CNPJ. Provavelmente deve usar o length da string para fazer essa verificação. O que evitaria esse problema.
A menos que o CNPJ estava em um tipo numérico e foi feito um ToString antes de passar para essa biblioteca. Se esse for o caso você precisa fazer um padding ou informar o formato com 14 dígitos no ToString.

**Comment by DanielSartori** [comment]
Opa, eu corrigi o problema, era na minha chamada, isso foi resolvido, mas o estranho que mesmo depois passando todos os dados certos o download do xml não ocorreu.

Eu vou pela consulta online no site da sefaz e funciona , mas pleno codigo para rodar na console e não vai , vou colocar aqui, se puder me ajudar agradeço imensamente !

Daniel

Enviado do meu iPhone

Em 22 de nov. de 2024, à(s) 21:02, Gustavo Rossi Müller ***@***.***> escreveu:

﻿

Boa noite,

Você pode mostrar o trecho de código onde isso está acontecendo? Estou pelo celular agora, mas costumo usar o tipo string para CNPJ. Provavelmente deve usar o length da string para fazer essa verificação. O que evitaria esse problema.
A menos que o CNPJ estava em um tipo numérico e foi feito um ToString antes de passar para essa biblioteca. Se esse for o caso você precisa fazer um padding ou informar o formato com 14 dígitos no ToString.

**Comment by DanielSartori** [comment]
Segue o meu código

[cid:702856be-af7f-43c5-b11a-643502e32577]

e a Resposta

[cid:f2d1dc38-5af3-4f0a-8dcb-7bb6acf59395]

________________________________
De: Gustavo Rossi Müller ***@***.***>
Enviado: sexta-feira, 22 de novembro de 2024 21:02
Para: GRMagic/Sefaz ***@***.***>
Cc: DanielSartori ***@***.***>; Author ***@***.***>
Assunto: Re: [GRMagic/Sefaz] Consistencia do CNPJ (Issue #29)


Boa noite,

Você pode mostrar o trecho de código onde isso está acontecendo? Estou pelo celular agora, mas costumo usar o tipo string para CNPJ. Provavelmente deve usar o length da string para fazer essa verificação. O que evitaria esse problema.
A menos que o CNPJ estava em um tipo numérico e foi feito um ToString antes de passar para essa biblioteca. Se esse for o caso você precisa fazer um padding ou informar o formato com 14 dígitos no ToString.

**Comment by DanielSartori** [comment]
Em tempo....

O Certificado é A1 e esta valido...

[cid:c662ffeb-5e1d-4a07-af25-38b6543125ec]

________________________________
De: Gustavo Rossi Müller ***@***.***>
Enviado: sexta-feira, 22 de novembro de 2024 21:02
Para: GRMagic/Sefaz ***@***.***>
Cc: DanielSartori ***@***.***>; Author ***@***.***>
Assunto: Re: [GRMagic/Sefaz] Consistencia do CNPJ (Issue #29)


Boa noite,

Você pode mostrar o trecho de código onde isso está acontecendo? Estou pelo celular agora, mas costumo usar o tipo string para CNPJ. Provavelmente deve usar o length da string para fazer essa verificação. O que evitaria esse problema.
A menos que o CNPJ estava em um tipo numérico e foi feito um ToString antes de passar para essa biblioteca. Se esse for o caso você precisa fazer um padding ou informar o formato com 14 dígitos no ToString.

**Comment by DanielSartori** [comment]
Cara desculpa ser chato...

Mas consegui resolver o problema e baixei o XML, fantástica sua solução...

O Problema era o Certificado, eu o importei no Windows e exportei ele de novo com todas as opções, aí passou a funcionar.

Vai ser de grande ajuda...

Valeu por ter compartilhado a solução...


________________________________
De: Gustavo Rossi Müller ***@***.***>
Enviado: sexta-feira, 22 de novembro de 2024 21:02
Para: GRMagic/Sefaz ***@***.***>
Cc: DanielSartori ***@***.***>; Author ***@***.***>
Assunto: Re: [GRMagic/Sefaz] Consistencia do CNPJ (Issue #29)


Boa noite,

Você pode mostrar o trecho de código onde isso está acontecendo? Estou pelo celular agora, mas costumo usar o tipo string para CNPJ. Provavelmente deve usar o length da string para fazer essa verificação. O que evitaria esse problema.
A menos que o CNPJ estava em um tipo numérico e foi feito um ToString antes de passar para essa biblioteca. Se esse for o caso você precisa fazer um padding ou informar o formato com 14 dígitos no ToString.

**Comment by GRMagic** [comment]
Que bom que você conseguiu resolver e que gostou do pacote! 🙂
